services:
  - type: web
    name: zentro
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn zentro.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: zentro.settings
